# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b53319f3b5a79b5b0cb8548fc041d0fa54485192f636eba7166b44547b85a9eeec8874932f330e2d6c99f3eeb7075c4a06ce9d5592d358ff337f075e4bb434bf

test:
  secret_key_base: 1c54b0a1a08f7c09d6c3dda037d981dda4cf354a32adc9dc2a5df3d231f02187728a01537aa8244062da478267d6784b3ee0a0be5b0b7ed002ae765745445f93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
